// <auto-generated />
namespace Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class setup_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setup_));
        
        string IMigrationMetadata.Id
        {
            get { return "202310282215165_setup_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
